# Generated by Django 3.2.18 on 2023-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_of_pupil', models.CharField(max_length=25)),
                ('surname_of_pupil', models.CharField(max_length=25)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('year_group', models.CharField(choices=[('0', 'Reception'), ('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Supper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supper_date', models.DateField()),
                ('confirmation', models.BooleanField()),
                ('pupil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil', unique_for_date='supper_date')),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_date', models.DateField()),
                ('confirmation', models.BooleanField()),
                ('pupil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil', unique_for_date='breakfast_date')),
            ],
        ),
    ]
