# Generated by Django 3.2.18 on 2023-04-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_of_pupil', models.CharField(max_length=25)),
                ('surname_of_pupil', models.CharField(max_length=25)),
                ('year_gp', models.CharField(choices=[('0', 'Reception'), ('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=1, verbose_name='Year group')),
                ('parent_name', models.CharField(max_length=50, verbose_name='Name of parent making booking')),
                ('parent_contact', models.CharField(max_length=12, verbose_name="Parent's preferred contact number")),
                ('contact_email_for_pupil', models.EmailField(max_length=254)),
                ('b_mon', models.BooleanField(default=False, verbose_name='Monday Breakfast')),
                ('b_tues', models.BooleanField(default=False, verbose_name='Tuesday Breakfast')),
                ('b_wed', models.BooleanField(default=False, verbose_name='Wednesday Breakfast')),
                ('b_thurs', models.BooleanField(default=False, verbose_name='Thursday Breakfast')),
                ('b_fri', models.BooleanField(default=False, verbose_name='Friday Breakfast')),
                ('s_mon', models.BooleanField(default=False, verbose_name='Monday Supper')),
                ('s_tues', models.BooleanField(default=False, verbose_name='Tuesday Supper')),
                ('s_wed', models.BooleanField(default=False, verbose_name='Wednesday Supper')),
                ('s_thurs', models.BooleanField(default=False, verbose_name='Thursday Supper')),
                ('s_fri', models.BooleanField(default=False, verbose_name='Friday Supper')),
                ('confirmation', models.BooleanField(default=False, verbose_name='I am aware that it costs £2/Breakfast and £2.50/Supper*')),
                ('booking_approval_status', models.CharField(choices=[('0', 'Pending Approval'), ('1', 'Approved')], default='0', max_length=1, verbose_name='Approval status')),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField(verbose_name='Date of Request')),
                ('approval_status', models.CharField(choices=[('0', 'Awaiting Approval'), ('1', 'Approved'), ('2', 'Declined: Club unavailable on requested date'), ('3', 'Declined: Insufficient notice')], default='0', max_length=2)),
                ('type_of_request', models.CharField(choices=[('0', 'Additional breakfast'), ('1', 'Additional supper'), ('2', 'Cancel breakfast'), ('3', 'Cancel supper')], max_length=2)),
                ('approved', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Date request was made')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil')),
            ],
        ),
    ]
