# Generated by Django 3.2.18 on 2023-03-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='contact',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='pupil',
            old_name='year',
            new_name='year_gp',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
    ]
