# Generated by Django 3.2.18 on 2023-03-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='parent_name',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
