# Generated by Django 3.2.18 on 2023-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
