# Generated by Django 3.2.18 on 2023-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_auto_20230306_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='bookclub',
            name='supper',
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='friday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='if_breakfast',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='if_supper',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='monday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='thursday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='tuesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='wednesday',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.DeleteModel(
            name='Supper',
        ),
    ]
