# Generated by Django 3.2.18 on 2023-03-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pupils', '0003_auto_20230305_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_fname', models.CharField(max_length=25)),
                ('parent_surname', models.CharField(max_length=25)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_of_pupil', models.CharField(max_length=25)),
                ('surname_of_pupil', models.CharField(max_length=25)),
                ('year', models.CharField(choices=[('0', 'Reception'), ('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Supper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supper_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_breakfast', models.BooleanField()),
                ('if_supper', models.BooleanField()),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('confirmation', models.BooleanField()),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.breakfast')),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.parent')),
                ('pupil_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil')),
                ('supper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.supper')),
            ],
        ),
    ]
