# Generated by Django 3.2.18 on 2023-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_bookclub_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_start_date', models.DateField(unique=True)),
                ('breakfast_end_date', models.DateField(unique=True)),
                ('breakfast_choice', models.CharField(choices=[('', '')], max_length=1)),
            ],
        ),
    ]
