# Generated by Django 3.2.18 on 2023-03-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0005_breakfast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='breakfast_choice',
        ),
    ]
