# Generated by Django 3.2.18 on 2023-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0007_auto_20230306_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_email',
            field=models.EmailField(default='xx@xx.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_no',
            field=models.CharField(max_length=11, verbose_name='Your contact number'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_fname',
            field=models.CharField(max_length=25, verbose_name='Your first name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_surname',
            field=models.CharField(max_length=25, verbose_name='Your surname'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='year_gp',
            field=models.CharField(choices=[('0', 'Reception'), ('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=1, verbose_name='Year group'),
        ),
    ]
