# Generated by Django 3.2.18 on 2023-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0008_auto_20230315_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='contact_email_for_pupil',
            field=models.EmailField(default='xxx@xxx.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='contact_number_for_pupil',
            field=models.CharField(default='00002', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='first_name_of_parent',
            field=models.CharField(default='First Name of Parent', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='surname_of_parent',
            field=models.CharField(default='Surname of Parent', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_no',
            field=models.CharField(max_length=12, verbose_name='Your contact number'),
        ),
    ]
