# Generated by Django 3.2.18 on 2023-03-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0009_auto_20230315_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='contact_number_for_pupil',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='first_name_of_parent',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='surname_of_parent',
        ),
    ]
