# Generated by Django 3.2.18 on 2023-03-16 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pupils', '0010_auto_20230315_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user_info',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
