# Generated by Django 3.2.18 on 2023-03-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pupils', '0011_parent_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='user_info',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
