# Generated by Django 3.2.18 on 2023-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0012_pupil_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='b_fri',
            field=models.BooleanField(default=False, verbose_name='Friday Breakfast'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='b_mon',
            field=models.BooleanField(default=False, verbose_name='Monday Breakfast'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='b_thurs',
            field=models.BooleanField(default=False, verbose_name='Thursday Breakfast'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='b_tues',
            field=models.BooleanField(default=False, verbose_name='Tuesday Breakfast'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='b_wed',
            field=models.BooleanField(default=False, verbose_name='Wednesday Breakfast'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='s_fri',
            field=models.BooleanField(default=False, verbose_name='Friday Supper'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='s_mon',
            field=models.BooleanField(default=False, verbose_name='Monday Supper'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='s_thurs',
            field=models.BooleanField(default=False, verbose_name='Thursday Supper'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='s_tues',
            field=models.BooleanField(default=False, verbose_name='Tuesday Supper'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='s_wed',
            field=models.BooleanField(default=False, verbose_name='Wednesday Supper'),
        ),
    ]
