# Generated by Django 3.2.18 on 2023-03-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0013_auto_20230322_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='parent_info',
            field=models.ForeignKey(default='20', on_delete=django.db.models.deletion.CASCADE, to='pupils.parent'),
            preserve_default=False,
        ),
    ]
