# Generated by Django 3.2.18 on 2023-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0014_pupil_parent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='pupil_info',
            field=models.ManyToManyField(to='pupils.Pupil'),
        ),
    ]
