# Generated by Django 3.2.18 on 2023-03-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0015_breakfast_pupil_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='pupil_info',
        ),
    ]
