# Generated by Django 3.2.18 on 2023-03-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0016_remove_breakfast_pupil_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_breakfast', models.DateField()),
                ('cancel_breakfast', models.DateField()),
                ('approved', models.BooleanField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil')),
            ],
        ),
    ]
