# Generated by Django 3.2.18 on 2023-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0017_breakfastrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastrequest',
            name='additional_breakfast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='cancel_breakfast',
            field=models.DateField(blank=True, null=True),
        ),
    ]
