# Generated by Django 3.2.18 on 2023-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0018_auto_20230327_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastrequest',
            name='additional_supper',
            field=models.DateField(blank=True, null=True, verbose_name='Date of additional supper (if applicable)'),
        ),
        migrations.AddField(
            model_name='breakfastrequest',
            name='cancel_supper',
            field=models.DateField(blank=True, null=True, verbose_name='Supper date you no longer require (if applicable)'),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='additional_breakfast',
            field=models.DateField(blank=True, null=True, verbose_name='Date of additional breakfast (if applicable)'),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='cancel_breakfast',
            field=models.DateField(blank=True, null=True, verbose_name='Breakfast date you no longer require (if applicable)'),
        ),
        migrations.AlterField(
            model_name='breakfastrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date request was made'),
        ),
    ]
