# Generated by Django 3.2.18 on 2023-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0020_daterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterequest',
            name='date_request',
            field=models.DateField(default='2024-12-12', verbose_name='Date of Request'),
            preserve_default=False,
        ),
    ]
