# Generated by Django 3.2.18 on 2023-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0022_alter_daterequest_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterequest',
            name='date_request',
            field=models.CharField(max_length=25, verbose_name='Your first name'),
        ),
    ]
