# Generated by Django 3.2.18 on 2023-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0024_alter_daterequest_date_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterequest',
            name='approval_status',
            field=models.CharField(choices=[('0', 'Awaiting Approval'), ('1', 'Approved'), ('2', 'Declined')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='daterequest',
            name='why_declined',
            field=models.CharField(choices=[('0', 'Awaiting Decision'), ('1', 'Club unavailable on requested date'), ('2', 'Insufficient notice')], default='0', max_length=1),
        ),
    ]
