# Generated by Django 3.2.18 on 2023-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0025_auto_20230328_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='parent_info',
        ),
        migrations.AlterField(
            model_name='daterequest',
            name='approval_status',
            field=models.CharField(choices=[('0', 'Awaiting Approval'), ('1', 'Approved'), ('2', 'Declined')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='daterequest',
            name='type_of_request',
            field=models.CharField(choices=[('0', 'Request an additional breakfast'), ('1', 'Request an additional supper'), ('2', 'Cancel existing breakfast'), ('3', 'Cancel existing supper')], max_length=2),
        ),
        # migrations.AlterField(
        #     model_name='daterequest',
        #     name='why_declined',
        #     field=models.CharField(choices=[('0', 'Awaiting Decision'), ('1', 'Club unavailable on requested date'), ('2', 'Insufficient notice')], default='0', max_length=2),
        # ),
    ]
