# Generated by Django 3.2.18 on 2023-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0026_auto_20230328_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='parent_contact',
            field=models.CharField(default='0770', max_length=12, verbose_name="Parent's preferred contact number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='parent_name',
            field=models.CharField(default='Lucy Loo', max_length=50, verbose_name='Name of parent making booking'),
            preserve_default=False,
        ),
    ]
