# Generated by Django 3.2.18 on 2023-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0027_auto_20230328_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='I am aware it is £2/Breakfast and £2.50/Supper'),
        ),
    ]
