# Generated by Django 3.2.18 on 2023-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0028_pupil_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='booking_approval_status',
            field=models.CharField(choices=[('0', 'Pending Approval'), ('1', 'Approved')], default='0', max_length=1, verbose_name='Approval status'),
        ),
        migrations.AlterField(
            model_name='daterequest',
            name='approval_status',
            field=models.CharField(choices=[('0', 'Awaiting Approval'), ('1', 'Approved'), ('2', 'Declined: Club unavailable on requested date'), ('3', 'Declined: Insufficient notice')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='confirmation',
            field=models.BooleanField(default=True, verbose_name='I am aware it is £2/Breakfast and £2.50/Supper'),
        ),
    ]
