# Generated by Django 3.2.18 on 2023-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0029_auto_20230329_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='daterequest',
            name='type_of_request',
            field=models.CharField(choices=[('0', 'Additional breakfast'), ('1', 'Additional supper'), ('2', 'Cancel breakfast'), ('3', 'Cancel supper')], max_length=2),
        ),
    ]
