# Generated by Django 3.2.18 on 2023-04-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0030_auto_20230403_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='bookclub',
            name='pupil_name',
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.RemoveField(
            model_name='breakfastrequest',
            name='pupil',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='BookClub',
        ),
        migrations.DeleteModel(
            name='BreakfastRequest',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
